### ISSUE TITLE
API Request: Get lucid data (electricity/steam/water) for a Building

### ISSUE THREAD

**Issue by dustinmichels** [carleton-cs-energy-analytics/energy-analytics-comps#42]
Chatting with Martin in the other (inferior) energy analytics group. They are only interested in Lucid data for a given building (electricity/steam/water), and don't want to have to know the pt names.

I think this could be useful for us too, since some visualizations/analysis may want to focus on that data?

Could we add an API call that just takes 'electric/steam/water' as a parameter, instead of a pt name? Maybe something like `$app->get('/building/:name/utility/:name')`. It also needs a time range. Thoughts?

**Comment by jacklightbody** [comment]
I believe this is already achievable by using the values of type query, as I think all the lucid data has a different point type than the Siemens data- though I could be wrong about that. Can also add a query on point source id if that proves not to work though.

**Comment by govekk** [comment]
Currently the type table is more of a dummy table to hold information on the data types of the point (e.x. units, float vs enum, factor). At the moment, there is no "electricity" data type. Once we have better tagging that might change, but for now it would be best to get electricity data by querying on the point source id (lucid), especially since we don't have siemens energy data yet.

**Comment by jacklightbody** [comment]
Ah, gotcha. I thought the point types table was much more filled in. I'll add a method
